name: ci-golang-workflow
on: [push, pull_request]
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go 1.23
      uses: actions/setup-go@v2
      with:
        go-version: 1.23
    - name: Run tests
      run: go test -v ./...
      run: go run math.go